version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: passive_nginx
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    expose:
      - "8000"
    networks:
      - passive
  web:
    build:
      context: .
    container_name: passive_web
    command: python manage.py runserver 0.0.0.0:8001
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=database
    depends_on:
      - database
    volumes:
      - ./app:/app
    expose:
      - "8001"
    networks:
      - passive

  database:
    image: mysql:5.7
    container_name: passive_database
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
    ports:
      - "33309:3306"
    volumes:
      - passive_mysql_data:/var/lib/mysql
    networks:
      - passive

volumes:
  passive_mysql_data:
    driver: local

networks:
  passive: