# Generated by Django 2.2 on 2020-10-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ads', models.BooleanField(default=False, verbose_name='Activación de Ads')),
                ('auto_ads', models.BooleanField(default=False, verbose_name='Activación de Ads automáticos')),
                ('adsense_id', models.CharField(blank=True, max_length=50, verbose_name='ID de Adsense')),
                ('ad_header', models.TextField(blank=True, verbose_name='Espacio superior')),
                ('ad_list', models.TextField(blank=True, verbose_name='Espacio entre elementos de una lista')),
                ('ad_footer', models.TextField(blank=True, verbose_name='Espacio inferior')),
                ('ad_sidebar', models.TextField(blank=True, verbose_name='Espacio lateral')),
            ],
            options={
                'verbose_name': 'Configuración de los espacios',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_seo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título del sitio (SEO)')),
                ('description_seo', models.TextField(blank=True, null=True, verbose_name='Descripción del sitio (SEO)')),
                ('keywords_seo', models.TextField(blank=True, null=True, verbose_name='Keywords del sitio (SEO)')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='slug (SEO)')),
                ('robots_seo', models.TextField(blank=True, null=True, verbose_name='Robots (SEO)')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Modo mantenimiento')),
                ('analytics_id', models.CharField(blank=True, max_length=50, verbose_name='ID de Google Analytics')),
                ('pagination', models.IntegerField(default=25, verbose_name='Paginación')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
            },
        ),
    ]
