# Generated by Django 2.2 on 2020-10-10 18:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=9999, null=True, verbose_name='Contenido')),
                ('is_category', models.BooleanField(default=False, verbose_name='Es categoría?')),
                ('created_by', models.ForeignKey(blank=True, help_text='Quien lo crea', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Crea')),
                ('updated_by', models.ForeignKey(blank=True, help_text='El último que lo actualizo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualiza')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_seo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título del sitio (SEO)')),
                ('description_seo', models.TextField(blank=True, null=True, verbose_name='Descripción del sitio (SEO)')),
                ('keywords_seo', models.TextField(blank=True, null=True, verbose_name='Keywords del sitio (SEO)')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='slug (SEO)')),
                ('robots_seo', models.TextField(blank=True, null=True, verbose_name='Robots (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', ckeditor.fields.RichTextField(max_length=50000, verbose_name='Contenido')),
                ('published', models.BooleanField(default=False, verbose_name='Publicada')),
                ('created_by', models.ForeignKey(blank=True, help_text='Quien lo crea', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Crea')),
                ('updated_by', models.ForeignKey(blank=True, help_text='El último que lo actualizo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualiza')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Atributo Title')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Enlace')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id de Objeto')),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Tipo de Objeto')),
            ],
            options={
                'verbose_name': 'Elemento de Menú',
                'verbose_name_plural': 'Elementos de Menú',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('placement', models.SmallIntegerField(blank=True, choices=[(1, 'Cabecera'), (0, 'Pie de página'), (2, 'Barra lateral')], verbose_name='Posición')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activado')),
                ('created_by', models.ForeignKey(blank=True, help_text='Quien lo crea', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Crea')),
                ('items', models.ManyToManyField(to='article.MenuItem')),
                ('updated_by', models.ForeignKey(blank=True, help_text='El último que lo actualizo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualiza')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_seo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título del sitio (SEO)')),
                ('description_seo', models.TextField(blank=True, null=True, verbose_name='Descripción del sitio (SEO)')),
                ('keywords_seo', models.TextField(blank=True, null=True, verbose_name='Keywords del sitio (SEO)')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='slug (SEO)')),
                ('robots_seo', models.TextField(blank=True, null=True, verbose_name='Robots (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', ckeditor.fields.RichTextField(max_length=9999, verbose_name='Contenido')),
                ('published', models.BooleanField(default=False, help_text='Para hacerla visible públicamente', verbose_name='Publicada')),
                ('created_by', models.ForeignKey(blank=True, help_text='Quien lo crea', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Crea')),
                ('tags', models.ManyToManyField(to='article.Tag')),
                ('updated_by', models.ForeignKey(blank=True, help_text='El último que lo actualizo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualiza')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
