# Generated by Django 2.2 on 2020-10-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201010_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_relevant',
            field=models.BooleanField(default=False, help_text='Para referenciar su enlace dentro de otros artículos', verbose_name='Relevante'),
        ),
    ]
