# Generated by Django 2.2 on 2020-10-11 17:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_article_is_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_seo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título del sitio (SEO)')),
                ('description_seo', models.TextField(blank=True, null=True, verbose_name='Descripción del sitio (SEO)')),
                ('keywords_seo', models.TextField(blank=True, null=True, verbose_name='Keywords del sitio (SEO)')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='slug (SEO)')),
                ('robots_seo', models.TextField(blank=True, null=True, verbose_name='Robots (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', ckeditor.fields.RichTextField(max_length=50000, verbose_name='Contenido')),
                ('published', models.BooleanField(default=False, verbose_name='Publicada')),
                ('created_by', models.ForeignKey(blank=True, help_text='Quien lo crea', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Crea')),
                ('updated_by', models.ForeignKey(blank=True, help_text='El último que lo actualizo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualiza')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
    ]
