# Generated by Django 2.2 on 2020-10-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Keywords únicos en el sistema del artículo'),
        ),
    ]
