# Generated by Django 2.2 on 2020-10-12 20:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=99999, verbose_name='Contenido'),
        ),
    ]
